### PR TITLE
Change flattenJSONObject to return POSIX compliant names

### PR DESCRIPTION
**Pull request by cbui**
Closes https://github.com/abhilash1in/aws-secrets-manager-action/issues/20

### CODE REVIEW

**Comment by cbui** [comment]
Should I remove the lock?

**Comment by abhilash1in** [comment]
@cbui Thank you for your contribution! 

> Should I remove the lock?

Yes, please. I'll update package-lock.json in a separate commit after bumping up a few dependencies.

The PR looks good on the first glance. Will take another look at merge it in.

**Comment by cbui** [comment]
Removed.

> @cbui Thank you for your contribution!

Thank you for this action 🥇

**Review by abhilash1in — APPROVED** [review]

**Comment by emmanuelnk** [comment]
@cbui @abhilash1in Just FYI I don't think this PR is working
image

**Pull request closed without merging**
